In [6]:
import numpy as np
np.__version__

'1.21.5'

## Numpy

In [7]:
# notasi  []
gpas_as_list = [4.0,3.0,3.5]
print(gpas_as_list)

[4.0, 3.0, 3.5]


In [8]:
gpas_as_list.append(4.0) #ditambah di ashkir list
print(gpas_as_list)

[4.0, 3.0, 3.5, 4.0]


In [9]:
gpas_as_list.insert(1,"NULL") #bisa kita taruh dimana kita mau ( letak, isi)
gpas_as_list

[4.0, 'NULL', 3.0, 3.5, 4.0]

In [10]:
gpas_as_list.pop(1) #pop itu akan menghaous list yan gkita pilih
gpas_as_list

[4.0, 3.0, 3.5, 4.0]

## Numpy Array 

In [11]:
gpas = np.array(gpas_as_list) # conver list ke array
gpas.dtype
gpas

array([4. , 3. , 3.5, 4. ])

In [12]:
gpas.size #jumlah data

4

In [13]:
gpas.shape

(4,)

## Demo aplikasi : Studi Log

In [14]:
#studi log
study_minute = np.zeros(100, np.uint16) #jumlah,type data
study_minute


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [15]:
#statistik variabel yg sudah ada
%whos

Variable             Type                          Data/Info
------------------------------------------------------------
NamespaceMagics      MetaHasTraits                 <class 'IPython.core.magi<...>mespace.NamespaceMagics'>
autopep8             module                        <module 'autopep8' from '<...>e-packages\\autopep8.py'>
get_ipython          function                      <function get_ipython at 0x00000155AB3511F0>
getsizeof            builtin_function_or_method    <built-in function getsizeof>
gpas                 ndarray                       4: 4 elems, type `float64`, 32 bytes
gpas_as_list         list                          n=4
json                 module                        <module 'json' from 'C:\\<...>\lib\\json\\__init__.py'>
np                   module                        <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
practice_list        list                          n=3
practice_list_copy   list                          n=3
study_minute        

## Demo multi dimensi array

In [16]:
students_gpas = np.array ([
    [4.0,3.3,3.5,4.0],
    [3.96,3.92,4.0,4.0],
    [3.2,3.8,4.0,4.0]
    
], np.float16)

students_gpas

array([[4.  , 3.3 , 3.5 , 4.  ],
       [3.96, 3.92, 4.  , 4.  ],
       [3.2 , 3.8 , 4.  , 4.  ]], dtype=float16)

In [17]:
students_gpas.ndim #number of fimensi

2

In [18]:
students_gpas.shape # 3 kolom/array, 4 baris/element

(3, 4)

In [19]:
students_gpas[2] # mengambil isi data array

array([3.2, 3.8, 4. , 4. ], dtype=float16)

In [20]:
students_gpas[2][3]

4.0

## Array Indexing : study log indexing

In [21]:
study_minute # 1 dimensi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [40]:
study_minutes = np.array([
    study_minutes,
    np.zeros(100, np.int16)
])
study_minutes.shape

C:\Users\ASUS\AppData\Local\Temp\ipykernel_10536\2914156011.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  study_minute = np.array([


(2,)

In [ ]:
study_minutes[1][0] = 60
study_minutes

In [ ]:
rand = np.random.RandomState(42)
fake_log = rand.randint(30,180,size = 100, dtype = np.int16) #random number, (start,end, size data yang ingin diisi, dtype)
print(fake_log)

In [ ]:
[fake_log[1],fake_log[21]] #jadi list

In [ ]:
fake_log[[1, 21]] # jadi array

In [ ]:
index = np.array ([
    [1,21],
    [1,2]
])

fake_log(index)

In [ ]:
study_minutes = np.append(study_minutes,[fake_log])
print(study_minutes)

## Slicing Array 

In [ ]:
practice = np.arange(42) # 0 - 41 urutan 0 - 41
practice.shape = (7,6) #terdiri dari 7 kolom/array dan 6 baris/item
practice#mencetak

In [ ]:
practice[2,1] #semua start dari 0 [array, item]

In [ ]:
practice[2:5]

In [ ]:
practice[2:5,3] #start array 2 sampai 5, di item ke 3 dari tiap array

In [ ]:
practice[2:5, 3:]#start array 2 sampai 5, di item ke 3 dan seterusnya

## Copy vs View 

> Copy = mengopy array
. view = menduplikasi tapi masih terpengaruh


In [32]:
#copy data, data baru di var baru bisa diubah isinya
practice_list = [1,2,3]
practice_list_copy = practice_list[:]
practice_list, practice_list_copy
practice_list_copy[0] = 12345
practice_list, practice_list_copy

([1, 2, 3], [12345, 2, 3])

In [33]:
practice = np.arange(42) # 0 - 41 urutan 0 - 41
practice.shape = (7,6) #terdiri dari 7 kolom/array dan 6 baris/item
practice#mencetak

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [34]:
#view
not_copy_but_view = practice[:] #ada relasi antara turunan dan data aslinya
not_copy_but_view[0,0] = 12345
practice, not_copy_but_view

(array([[12345,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]),
 array([[12345,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]))

In [30]:
print(practice.base)

None


In [31]:
print(not_copy_but_view.base)

[[12345     1     2     3     4     5]
 [    6     7     8     9    10    11]
 [   12    13    14    15    16    17]
 [   18    19    20    21    22    23]
 [   24    25    26    27    28    29]
 [   30    31    32    33    34    35]
 [   36    37    38    39    40    41]]


In [36]:
not_copy2 = practice.view()
not_copy2,practice

(array([[12345,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]),
 array([[12345,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]))